name: ipannotoryus

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.8,<3.9.0a0
  - jupyterlab >=3,<4.0.0a0
  - jupyter-packaging >=0.7.9,<0.8.0
  # labextension build dependencies
  - nodejs >=14,<15
  - yarn
  - pip
  - wheel
  # Fix binder
  - ipywidgets >=7.6.0
