name: ipannotoryus

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.8,<3.9.0a0
  - jupyterlab >=2,<3.0.0a0
  # labextension build dependencies
  - nodejs >=14,<15
  - pip
  - wheel
  # Fix binder
  - ipywidgets
